# Generated by Django 4.0.2 on 2022-02-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
