# Generated by Django 4.0.2 on 2022-02-27 11:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_alter_newuser_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
