# Generated by Django 4.0.2 on 2022-03-03 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_blogpostmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpostmodel',
            old_name='user',
            new_name='user_id',
        ),
    ]
