# Generated by Django 4.0.2 on 2022-03-05 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_rename_user_blogpostmodel_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='user_image',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
