# Generated by Django 4.0.2 on 2022-03-05 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_newuser_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='user_image',
            field=models.ImageField(blank=True, upload_to=models.EmailField(max_length=254, unique=True)),
        ),
    ]
